# Where should we write the GIF?
Output demo.gif

# Set up a 1200x600 terminal with 46px font.
Set FontSize 20
Set Width 1200
Set Height 600

# Clean the preview for next command
Hide
Sleep 1s
Ctrl+L
Show

# Type a command in the terminal.
Type "node days/day1.js"

# Pause for dramatic effect...
Sleep 500ms

# Run the command by pressing enter.
Enter

# Clean the preview for next command
Sleep 10s